name: Jekyll Build Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true
        working-directory: ./blog

    - name: Install dependencies
      run: |
        cd blog
        bundle install

    - name: Build Jekyll site
      run: |
        cd blog
        bundle exec jekyll build --trace
